name: Go CI

on:
  push:
    paths:
      - '.github/workflows/go-ci.yml'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    paths:
      - '.github/workflows/go-ci.yml'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: go-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@main

    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#    with:
#      code_coverage: true
#      min_test_coverage_percent: 100